#!/usr/bin/python

if __name__=='__main__':
    import hddm
    import sys
    import os
    if len(sys.argv) == 1 or sys.argv[1] == '-h' or sys.argv[1] == '--help':
        print "hddmfit --data <data.csv> <model.cfg>"
        sys.exit(-1)

    if sys.argv[1] == '--data' or sys.argv[1] == '-d':
        data_fname = sys.argv[2]
        config_fname = sys.argv[3]
    else:
        data_fname = None
        config_fname = sys.argv[1]
        
    hddm.utils.parse_config_file(config_fname, data=data_fname)
