#!/usr/bin/python

if __name__=='__main__':
    import hddm
    import sys
    import os
    if len(sys.argv) == 1 or sys.argv[1] == '-h' or sys.argv[1] == '--help':
        print "hddmfit [-l] <model.cfg>"
        print "-l: load previous samples from database. Does not run MCMC."
        sys.exit(-1)

    if sys.argv[1] == '-l':
        mcmc=False
        config_fname = sys.argv[2]
    else:
        mcmc=True
        config_fname = sys.argv[1]
        
    hddm.utils.parse_config_file(config_fname, mcmc=mcmc)
